name: build wheels
on:
  workflow_dispatch:
jobs:
  build_wheels:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: cibuildwheel installation
        run: python -m pip install cibuildwheel==1.11.0 twine
        
      - name: Install gcc on MacOS
        if: matrix.os == 'macOS-10.15'
        run: |
          brew install gcc@11
          gcc-11 -v

      - name: build specified wheels
        run: |
          if [[ ${{ matrix.os }} == macOS-10.15 ]]; then
            echo "CC=gcc-11" >> $GITHUB_ENV
          fi
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
          CIBW_BEFORE_BUILD: python -m pip install cython numpy
          
      - name: upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m twine upload dist/*.whl
