name: build wheels python 3.6 to 3.8
on:
  workflow_dispatch:
jobs:
  build_wheels:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: cibuildwheel installation
        run: python -m pip install cibuildwheel==1.11.0 twine
          
      - name: build specified wheels on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*
          CIBW_BEFORE_BUILD: python -m pip install cython==3.0.12
          
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
